version: '3'
services:
    nginx:
        image: nginx
        volumes:
            - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ../apirx:/var/www/html/clinicarx.api
            - ../app:/var/www/html/clinicarx.app
        ports:
            - 80:80
        restart: always
        depends_on:
            - php
            - postgres
    php:
        build: .docker
        restart: always
        environment: 
            - XDEBUG_CONFIG=remote_host=host.docker.internal
        volumes:
            - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ../apirx:/var/www/html/clinicarx.api
            - ../app:/var/www/html/clinicarx.app
    postgres:
        image: postgres:9.6
        restart: always
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - 55432:5432
        volumes:
            - ./.docker/conf/postgres/:/docker-entrypoint-initdb.d/
            - ../db:/db
            - ../apirx:/var/www/html/clinicarx.api
